### ISSUE TITLE
Authentication of OpenC2 Message

### ISSUE THREAD

**Issue by alevere** [oasis-tcs/openc2-impl-https#103]
Myself and @jmgnc propose that the TCS consider expanding section 3.2.4 Authentication to include a subsection that defines a method for a consumer to digitally sign an OpenC2 request. For example, please see https://docs.aws.amazon.com/general/latest/gr/signing_aws_api_requests.html . This would allow for a consumer or actuator to know that the message it received was initiated by a trusted resource and was not tampered with in-flight. I think it would be useful to describe a preferred mechanism for handling authentication in the transport spec for HTTPS. I expect that this would be desired by orchestrators, such that they could implement a more standard way to authenticate to a consumer.

**Comment by dlemire60** [comment]
I agree we should specify some means to provide source authentication and integrity of OpenC2 commands (and responses?) transmitted via HTTPS.  Some questions:

- Should signatures be required or optional?
- Would certificate-based mutual TLS authentication provide equivalent protection? (i.e., how do we strike a balance between security applied to OpenC2 messages and security provided by the transfer protocol?)
- Since the reference approach is AWS-specific (which isn't to suggest it isn't sound), is there a recognized standard we should adopt?

**Comment by jmbrule** [comment]
Signatures should be OPTIONAL.  An authenticated link may be provided by a range of mechanisms, thus 'require' a signature on they payload it is redundant. 
The decision to balance the security applied to the openc2 message and the risk management decision belongs to the mission owner, therefore not appropriate for the specification.  
ALL approaches should be based on recognized standards.

**Comment by jmbrule** [comment]
sigh, old version of firefox and cannot edit....  
Top sentence should be: ...authenticated link may be provided by a range of mechanisms, thus to 'require' a signature on the payload may be redundant and add unnecessary complexity.

**Comment by Vasileios-Mavroeidis** [comment]
and just to archive what i remember from our discussion, @jmgnc mentioned something about signing OpenC2 payloads and including the key in the JSON object. Maybe he can elaborate.

**Comment by dlemire60** [comment]
> and just to archive what i remember from our discussion, @jmgnc mentioned something about signing OpenC2 payloads and including the key in the JSON object. Maybe he can elaborate.

@jmgnc was referring to JSON Signature Format:  https://cyberphone.github.io/doc/security/jsf.html

It does look like a good fit for (some of) our needs, however it does not appear to be associated with any formal standards body, which is a disadvantage. It's also dependent on a JSON canonicalization solution that's currently still an Internet Draft.

**Comment by jmbrule** [comment]
I would prefer (strongly prefer) an actual standard, or at least on a standards track within a standards body

**Comment by dlemire60** [comment]
This requirement is being addressed through work on message signatures in the OpenC2 Language Specification.

LS Issue 362 describes a requirement for signatures for message integrity:  
https://github.com/oasis-tcs/openc2-oc2ls/issues/362

Language describing a signature solution was added to the LS working branch in PR 372:
https://github.com/oasis-tcs/openc2-oc2ls/pull/372

The Internet Draft describing the JSON canonicalization scheme was promoted to RFC status in June 2020 and is now RFC 8785:
https://datatracker.ietf.org/doc/html/rfc8785
That document's history is here:  https://datatracker.ietf.org/doc/rfc8785/history/

Given the work on this issue in the language specification, I propose closing this issue against the HTTPS spec.

**Comment by dlemire60** [comment]
Discussed this issue during 30 June 2021 working meeting and agreed to close the issue, defer the solution to the Language Specification.
