### ISSUE TITLE
Examples message dates should be illustrative (HTTPS-3)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#11]
Message examples should use example dates rather than a template, to match the other fields in the examples. Currently the Date field is the one with a template. 

Suggest that the example command and response messages and should have representative date values rather than a date-time format template. This applies to all example messages in Annex B, i.e., P19, L35; P20, Ls 4, 13, 31, 46, 55.

**Comment by sparrell** [comment]
I agree examples in specification should have real data in them (eg "Thu, 6 Dec 2018 09:18:00 GMT" instead of "Day, DD Mon YYYY HH:MM:SS GMT")

**Comment by dlemire60** [comment]
Accepted pull request. Closing issue as this is a non-material change to non-normative examples.
