### ISSUE TITLE
Update Message structure

### ISSUE THREAD

**Issue by davaya** [oasis-tcs/openc2-impl-https#110]
The message structure in section 3.3.2 should be updated to reflect language spec PR #370 https://github.com/oasis-tcs/openc2-oc2ls/pull/370.  Interestingly the 370 structure is shown in the "fonts and colors" example but not in the body.

**Comment by dlemire60** [comment]
Once approved, the message structure content in [MQTT PR 36](https://github.com/oasis-tcs/openc2-transf-mqtt/pull/36) will be used to update the HTTPS specification to the "modern" OpenC2 message structure

**Comment by dlemire60** [comment]
This issue was addressed by PR #115 which was approved at the 8/4/2021 working meeting.
