### ISSUE TITLE
Change "specification describes" to "document specifies" in Abstract (HTTPS-6)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#14]
Proposed new wording:  "This document specifies the use of HTTP over TLS as a transfer mechanism for OpenC2 messages."

Specifying is a stronger word that 'describe' and 'this specification describes ...' reads poorly

**Comment by jmbrule** [comment]
Agreed

**Comment by dlemire60** [comment]
Merge pull request. Closing issue as this is a minor wording change in non-normative text.
