### ISSUE TITLE
Delete "one or more" regarding selection of transfer specifications. (HTTPS-7)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#15]
Suggested Change:  Delete "one or more" in phrase "should select one or more transfer specifications"

Justification:  Running dual or multiple stacks is probably going to be an edge case, so no need to highlight it here when simply stating selecting transfer specifications concisely captures the thought.

**Comment by jmbrule** [comment]
Agreed

**Comment by dlemire60** [comment]
OBE with the use of common content for Section 1.  Closing issue.
