### ISSUE TITLE
Clarify explanation of layering of security solutions (HTTPS-10)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#18]
Suggested Change:  Reword sentence describing layering as notional for greater clarify.  Suggestion:  "Note that the layering of implementation aspects in the diagram is notional, and not intended to preclude any particular approach to implementing the needed functionality (for example, the use of an application-layer message signature function to provide message source authentication and integrity)."

Justification:  Reword to be more general, with illustrative example

**Comment by jmbrule** [comment]
Agreed, we got the same comment in the SLPF

**Comment by dlemire60** [comment]
Updated by PR #62 which pulls in common Section 1 content.
