### ISSUE TITLE
Remove references to the subcommittees in the layering figure (HTTPS-11)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#19]
Suggested Change:  Remove references to the subcommittees in the figure

Justification:  The section addresses scope of the different specifications, the organization of the TC is not relevant in that context.

**Comment by jmbrule** [comment]
Agree with the reviewer and we got the same comment in the SLPF.

**Comment by dlemire60** [comment]
Updated by PR #62  which pulls in common Section 1 content.
