### ISSUE TITLE
Change "transport" to "transfer" (HTTPS-12)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#20]
Suggested Change:  Change "transport" to "transfer" in phrase "as a transport mechanism for"

Justification:  Application layer protocols describe information transfer (ref: SMTP, FTP), whereas transport is a Layer 4 function.

**Comment by jmbrule** [comment]
Agree with reviewer in this matter.

**Comment by dlemire60** [comment]
This issue was discussed at the January 2019 F2F. The question raised was when "transfer" replaced "transport", as the TC charter uses the term "transport". The editor noted that he's consistently used transfer, consistent with other application layer protocols such as FTP, SMTP, and HTTP, where the "T" in each is "transfer". The consensus of the room was to be consistent with the IETF language, along with a recommendation to be explicit about terms, define them, and provide appropriate references.  The editor will need to enhance PR #39 to address the definition and reference aspects.

**Comment by dlemire60** [comment]
Addressed in PR #62
