### ISSUE TITLE
Reword sentence for broader audience (HTTPS-13)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#21]
Suggested Change:  Reword sentence "This specification provides ..." to address audiences beyond implementers.  Suggestion: "This specification provides guidance for selection of TLS versions and options when utilizing HTTPS for OpenC2 message transport." and delete subsequent sentence starting "It includes guidance ...".

Justification:  More that just the implementation community, can also provide guidance to system integrator, even architects and acquisition community. Deleted sentence intent now covered in reworded sentence.

**Comment by jmbrule** [comment]
Agree with the reviewers comment

**Comment by dlemire60** [comment]
PR merged, closing issue.
