### ISSUE TITLE
Remove "JSON" from message lines in Figures 2 and 3 (HTTPS-14)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#22]
Suggested Change:  Remove "JSON" from description of command and response messages in Figures 2 and 3.

Justification:  We should keep the diagram as general as practical and NOT preclude other serializations.

**Comment by jmbrule** [comment]
Agree with the reviewer in this matter.

**Comment by dlemire60** [comment]
The was discussed at the January 2019 F2F and the consensus was to reject this change. While the specification language will be changed to "support" rather than "use" JSON  (Issue #10), it is still the case that JSON is required for conformance, and the group felt the diagrams should continue to reflect that.

**Comment by dlemire60** [comment]
Given the F2F consensus and the cancellation of the associated pull request, I'm closing this issue.
