### ISSUE TITLE
Ballot Comment - Restful API

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-impl-https#3]
The  HTTPS CSD ballot spec states:
`Note that this specification does not describe the use of HTTPS to access a RESTful application programming interface (API) for OpenC2.`
Is the spec written such that it CAN NOT be used for a rest API? 
Or is just the fact that transferring messages is independent of whether the producer/consumer API is restful? Ie I could make a restful API that complied with this spec, but complying with this spec doesn't make it restful. 
Either way, I think the wording should clarify what is meant.
I am worried because the main use I see for this spec is to virtual security technology in the cloud, all of which to my knowledge use restful api's (AWS, Azure, Symantec, McAfee, Cisco, Juniper, etc ad infinitum). It would be a showstopper for me if this spec can not be used for rest api's.

There apparently is some debate on defining a rest API. My definition is whatever the vendors are using. Some example rest api's to current security technology:

- AWS - https://docs.aws.amazon.com/apigateway/api-reference/
- Azure - https://docs.microsoft.com/en-us/rest/api/azure/
- Openstack - https://developer.openstack.org/api-guide/quick-start/
- Palo Alto - http://www.csuc.cat/sites/default/files/docs/albertestevez_einamigracioregles.pdf
- Cisco - https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/2-x/rest_cfg/2_1_x/b_Cisco_APIC_REST_API_Configuration_Guide.html
- Juniper - https://www.juniper.net/documentation/en_US/junos/information-products/pathway-pages/rest-api/rest-api.html
- Fortinet - https://docs.fortinet.com/d/fortiauthenticator-rest-api-solution-guide
- Symantc - https://support.symantec.com/en_US/article.DOC9447.html
- McAfee - https://kc.mcafee.com/corporate/index?page=content&id=PD24810

I am voting no unless this statement is removed and replaced with text showing that it's at least possible to use this spec to interface vendors claiming rest api's such as those listed above.

**Comment by jmbrule** [comment]
When I read the sentence in question, I interpreted it as the specification does not require a RESTful interface, but by the same token, it does not PRECLUDE a restful interface.  I think the underlying issue is that in the academic sense of the word, the actuator (or in openc2-speak the openc2 consumer) is prohibited from maintaining any state info about the session.  As written, I do not see the proposed spec precluding the use of RESTful interface, simply does not require.  
Given the different interpretations, we need to clarify the section.

**Comment by jmgnc** [comment]
I think the sentence should just be removed.  I don't see how the implementation isn't REST compliant as I understand it.

**Comment by dlemire60** [comment]
The sentence has been removed and (as best I can tell) there seems to be a consensus that addresses the issue, so I'm closing this one.
