### ISSUE TITLE
Remove notifications (HTTPS-21)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#46]
Duncan Sparrell [wrote](https://lists.oasis-open.org/archives/openc2/201812/msg00049.html): 
> Section 3.1 - Notification should be removed. It is presumptuous to include and implies a solution not yet agreed to. I disagree with OpenC2 encroaching into Alerting where other specifications already exist.

**Comment by jmbrule** [comment]
Agree with the reviewer.  The idea of 'proactively' addressing notification when the concept is not introduced elsewhere does nothing but add confusion.  'Message' is just the payload, so no need to provide detail regarding the payload.

**Comment by dlemire60** [comment]
Have created PR #52 to address this comment.

**Comment by jmbrule** [comment]
Based on the IC-SC telecon that took place on 1/2/2019, the IC SC recommends removing the notification reference from this spec

**Comment by dlemire60** [comment]
This was discussed at the January 2019 F2F and the PR language was presented.  The consensus of the F2F meeting was to approve this change, with no one speaking against it.

**Comment by dlemire60** [comment]
Merged pull request.
