### ISSUE TITLE
command-id vs. request-id (HTTPS-22)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#47]
Duncan Sparrell [wrote](https://lists.oasis-open.org/archives/openc2/201812/msg00050.html):
>Although I agree with the current wording (ie use of "command-id"), presuming I lose the argument in other comments, then "command-id" should change to "request-id"

**Comment by jmbrule** [comment]
This comment is confusing.  Is the suggestion for a global replacement of 'command-id' with 'request-id' and why?

**Comment by dlemire60** [comment]
I believe the comment is to make the terminology in the HTTPS spec consistent with the L-Spec, assuming there isn't a bigger change regarding creation and communication of "command-id".

See L-Spec [issue 151](https://github.com/oasis-tcs/openc2-oc2ls/issues/151) for the larger discussion.

**Comment by dlemire60** [comment]
PR #63 updates the HTTPS Spec to align with the Language Spec on this issue. I am closing this issue based on having achieved alignment.
