### ISSUE TITLE
X-Correlation-ID details (HTTPS-29)

### ISSUE THREAD

**Issue by dlemire60** [oasis-tcs/openc2-impl-https#54]
Dave Lemire [wrote](https://lists.oasis-open.org/archives/openc2/201812/msg00069.html): 
> The HTTPS Transfer Specification does not define an encoding value for the X-Correlation-ID that is used to convey the OpenC2 request_id.
>
> The OpenC2 Language Specification
> 1) defines request-id as a binary value with a specific maximum size of 128 bits (Section 3.1.2),
> and
> 2) Specifies base64url encoding for binary values.
> HTTP headers are strings. In the absence of other constraints, the HTTPS Specification should specify base64url encoding for the request-id value carried in the X-Correlation-ID.
Note: binary encoding is specified in [Section 3.1.5](http://docs.oasis-open.org/openc2/oc2ls/v1.0/csprd01/oc2ls-v1.0-csprd01.html#315-serialization) of the Language Specification.

**Comment by jmbrule** [comment]
I agree with the modifications made in pull request number 55

**Comment by dlemire60** [comment]
This issue was discussed at the January 2019 F2F meeting and the consensus of the participants was in favor of this change.

**Comment by sudeepd** [comment]
From a semantic standpoint, base64-ed 128 bits and guids are equivalent. From an implementation standpoint however, I see the possibility of implementors representing this field as a 128 bit number or a combination of 2 64 bit ints, and then tripping up in byte order / endianness issues.
Guids are a representation of 128 bits as well, and extensive tooling exists for handling guids, and the chances of error reduce with use of guids for this field. Also consider support for this datatype in database storage engines.
Propose changing this field to a guid as described in https://tools.ietf.org/html/rfc4122

**Comment by dlemire60** [comment]
@sudeepd: I think the questions of 
* what the "0-128 bit" value is and 
* the transfer encoding of that value 

are distinct items, although I take your point about interoperability. The form of the identifier value type (being renamed "rcid" in the Language Spec) is a language-level issue. The encoding of it is a transfer spec issue. There has been resistance in the past to just making the identifier a 128-bit UUIDv4, mostly in the context of lighterweight devices or constrained bandwidth networks.

**Comment by sudeepd** [comment]
@dlemire60 
I agree that the two are separate in terms of language and encoding, and I am in agreement on the language aspects. 
It seems somewhat paradoxical that we have a verbose transfer (https), and we are optimizing for bandwidth constraints. I agree that there are pros and cons to 128 bit uuid, and wanted to have them considered before arriving at a decision. If this has already been discussed and decided then lets just have it stand the way it is.

**Comment by dlemire60** [comment]
This issue has been overcome by events. In pull request 248 for the Language Specification, the command-id and request-id types have been changed to string, so there's no longer a need to apply base64url encoding. As the PR #55 has already been merged, further changes for consistency between the Language and HTTPS specifications will be addressed in a new pull request for this specification.

https://github.com/oasis-tcs/openc2-oc2ls/pull/248

**Comment by dlemire60** [comment]
PR #63 has been created to address changes needed for alignment with the L-Spec. It: 

- aligns the HTTPS specification content with recent changes in the Language Spec regarding handling of request_id
- changes selected header from X-Correlation-ID to X-Request-ID (per input from DaveK and  BrianB)
- plus does a little clean-up on the Conformance section (removing references to sections removed with the removal of the polling model)

Discussed at the 20 Feb IC-SC meeting, and participants approved of these changes.

**Comment by dlemire60** [comment]
PR #63 applied, closing issue.
