### ISSUE TITLE
Authentication Requirements (HTTPS-27)

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-impl-https#6]
Section 3.2.3 states 
`When mutual authentication is used, endpoints MUST perform full path validation on each certificate, as defined in [RFC5280]`
Implicit in this statement is a particular way of doing mutual authentication (ie per RFC5280 certificates). There are other ways to do mutual authentication and I think they should be allowed. I think mutual authentication MUST be done (a different ballot comment) but I think the methods of mutual authentication should be optional, or we should specify several different ways not limited to REFC5280 but also including Single Packet Authentication (SPA) as defined in the Cloud Security Alliance (CSA) Software Defined Perimeter (SDP).

**Comment by dlemire60** [comment]
This was discussed at the October 2018 face-to-face. The consensus was that 

- certificates are the preferred authentication mechanism with HTTPS
- fallback from mutual certificate authentication was essential in some environments
- the use of CSA SPA should be define in a separate transfer specification

**Comment by dlemire60** [comment]
This has been raised again as a PR01 comment and will be addressed as such.

https://lists.oasis-open.org/archives/openc2/201812/msg00058.html

**Comment by dlemire60** [comment]
This was discussed at the 19 Dec 2018 IC-SC meeting (attendees were Lemire, Brule, Considine, Kemp, Martinez, Sparrell). Consensus of the meeting was **supportive** of eliminating the specific requirement for use of X.509 certificates as the mechanism for mutual authentication. Supporting rationales included:

- There are a variety of old (e.g., X.509) and new (e.g., CSA SPA) authentication mechanisms available to draw on.
- It is appropriate that the OpenC2 standards support a range of mechanisms
- It is premature for the OpenC2 TC to enumerate support for specific mechanisms
- Interoperability concerns can be addressed via developing conformance clauses aligned with individual mechanisms

**Comment by dlemire60** [comment]
Changes I believe are needed for this issue:

- Remove the final sentence of section 3.2.3 that requires full path validation of certificates (PDF version P11, L54-55)
- Remove the reference to public key certificates and path validation in the conformance section 4.2 (PDF P17, L45-46)
- Remove RFC5280 as a reference

**Comment by dlemire60** [comment]
What I believe is an open question right now:  if requirements for any specific authentication mechanism are removed from the HTTPS spec, what conformance requirements can we apply to mutual authentication, and what basis do we have for defining interoperability (never mind testing for it).

**Comment by dlemire60** [comment]
This was discussed at the January 2019 F2F and the PR language was presented. This issue was discussed in conjunction with Issue #5  (HTTPS-26)  The consensus of the F2F meeting was to approve this change. While the two issues are distinct it proved difficult to discuss them in isolation. The language generally agreed to at the meeting was "each party to an openc2 communication must authenticate the other party" (credit Toby Considine), that authentication might be handled by mechanisms outside of TLS, and that the TC was not in a position to specify mechanisms.  The editor will withdraw the current PRs for HTTPS-26 and -27, and submit a revised PR with changes to address both issues.

**Comment by dlemire60** [comment]
Per the discussion at the 6 February IC-SC meeting, I am applying PR #58 and closing this issue.
