### ISSUE TITLE
Ballot Comment WD02 - correlation_id

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-impl-https#7]
Section 4 (Conformance) contains a statement that conforming implementations must conform with the OpenC2 Language Specification and carry the correlation_id in the HTTP X-Correlation-ID header. There is still debate in the LSC about correlating content inside the message with HTTP header information. I am against crossing layer boundaries and making json content of the command dependent on information from the transport layer. However if I lost that argument, then I believe the transport should be dependent on the command, not the command dependent on the transport. That would require changes to this conformance statement and should also require some text in the body of this document stating the http header X-Correlation-ID is dependent on the command-id.

**Comment by dlemire60** [comment]
WD02 wording is that "correlation_id" is "Carried in HTTP X-Correlation-ID header". Consensus at October face-to-face was to split the ID into separate request_id and response_id. Both of those values are generated in the OpenC2 "layer" and conveyed by the transfer protocol. Changing the HTTPS table wording in WD03-wip to "Value supplied by OpenC2 Producer / Consumer is carried in the HTTP X-Correlation-ID and delivered to recipient along with OpenC2 command / response". Hopefully this clarifies that the transfer is the dependent layer.

**Comment by davaya** [comment]
The Language Spec section 3.2 defines message element request_id.  That value is generated by the producer, transferred to the consumer, and copied by the consumer from the request into the response.  The HTTP spec says that request_id is mapped to the X-Correlation-ID HTTP header.  That applies to all messages - requests, responses, and (if any) unsolicited notifications.

The Language Spec does not define a response_id message element.  If a use case for such a value is articulated it can be added to the Language Spec, at which point all Transfer Specs would need to define how to support it, including defining a custom HTTP header to carry it.   I haven't seen such a use case.

The use case of distinguishing multiple responses to a single command (articulated by Danny Martinez where he called it "actuator_id") is addressed by the "from" message element.  Each consumer generating a response puts its id in the "from" field.

**Comment by dlemire60** [comment]
WD02 has been superceded. This topic is now addressed in comments to the public review draft 01 versions of the documents. The overarching comment is captured in Language Spec Issue [151](https://github.com/oasis-tcs/openc2-oc2ls/issues/151).

Related comments on the HTTPS specification are in issues  #43, #45, and  #47,

I am closing this issue and the topic will be addresses as part of public review comment resolution.
