### ISSUE TITLE
HTTP header dates should not be required (HTTPS-2)

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-impl-https#8]
In Section 3.3, the HTTP request and response headers include dates which are required ("MUST"). Recommend that it be changed to a "SHOULD" to allow for the use-cases that do not need to send date information.

**Comment by alevere** [comment]
I agree, I dont see the date as required for the functionality we needed in the slpf.

**Comment by dlemire60** [comment]
The pull request (https://github.com/oasis-tcs/openc2-impl-https/pull/9) only addresses the HTTP Date headers in Section 3.3; also need the equivalent changes in 3.4.

Also, will want to apply those changes to the newly declared _csd04_ branch (AKA PRD01 comment resolutions) rather than the master.

**Comment by sparrell** [comment]
I (Duncan Sparrell) agree with changing the date field to optional.

**Comment by dlemire60** [comment]
Addressed inn PR #30

**Comment by davaya** [comment]
An actuator that supports the HTTPS transfer spec MUST be a valid HTTP server.

https://tools.ietf.org/html/rfc7231#section-7.1.1.2 specifies the cases where the Date header MUST NOT, MAY, and MUST be sent.

The conformance requirements should say that the Date header MUST be sent in accordance with the RFC.   The transfer spec may restate the RFC requirements as a non-normative explanation.

**Comment by alevere** [comment]
As I read the implementation, it is saying one MUST send the date header. However, that is not what the RFC says. The RFC says you can send a date header. It may be best to simply say refer to the RFC regarding date headers.


Note that I read "MUST be sent ... " as not as clear as simply follow the RFC regarding date headers. The first sounds more like you are required to send something.


-Alex

________________________________

**Comment by dlemire60** [comment]
This was discussed at the January 2019 F2F meeting. The consensus was that the IETF had already done the work regarding population of this field and that the HTTPS transfer specification should reference the appropriate RFC content as guidance. The editor was directed to make the reference to specific RFC section(s).

**Comment by dlemire60** [comment]
I've updated PR #30 to point to RFC 7231, Section 7.1.1 for date format and conditionals.

**Comment by dlemire60** [comment]
Per consensus at the 6 February IC-SC meeting, I'm applying PR #30 and closing this issue.
