### ISSUE TITLE
"Cache-control" header no-cache

### ISSUE THREAD

**Issue by Vasileios-Mavroeidis** [oasis-tcs/openc2-impl-https#98]
The specification in Section 3.2.2 "HTTP Usage" recommends the use of "Cache-control" http header with a value "no-cache" without giving an explanation as to why the no-cache value is preferred in relation to "no-store". 

If the requirement is to avoid storing any request or response in any of the systems engaged at an OpenC2 transaction then the no-store value should be used. If the requirement is something else then maybe it needs to be specified.

According to:  https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.2

**no-cache**
If the no-cache directive does not specify a field-name, then a cache MUST NOT use the response to satisfy a subsequent request without successful revalidation with the origin server. This allows an origin server to prevent caching even by caches that have been configured to return stale responses to client requests.

If the no-cache directive does specify one or more field-names, then a cache MAY use the response to satisfy a subsequent request, subject to any other restrictions on caching. However, the specified field-name(s) MUST NOT be sent in the response to a subsequent request without successful revalidation with the origin server. This allows an origin server to prevent the re-use of certain header fields in a response, while still allowing caching of the rest of the response.
**Note: Most HTTP/1.0 caches will not recognize or obey this directive.**

**no-store**
The purpose of the no-store directive is to prevent the inadvertent release or retention of sensitive information (for example, on backup tapes). The no-store directive applies to the entire message, and MAY be sent either in a response or in a request. If sent in a request, a cache MUST NOT store any part of either this request or any response to it. If sent in a response, a cache MUST NOT store any part of either this response or the request that elicited it. This directive applies to both non- shared and shared caches. "MUST NOT store" in this context means that the cache MUST NOT intentionally store the information in non-volatile storage, and MUST make a best-effort attempt to remove the information from volatile storage as promptly as possible after forwarding it.
Even when this directive is associated with a response, users might explicitly store such a response outside of the caching system (e.g., with a "Save As" dialog). History buffers MAY store such responses as part of their normal operation.
The purpose of this directive is to meet the stated requirements of certain users and service authors who are concerned about accidental releases of information via unanticipated accesses to cache data structures. While the use of this directive might improve privacy in some cases, we caution that it is NOT in any way a reliable or sufficient mechanism for ensuring privacy. In particular, malicious or compromised caches might not recognize or obey this directive, and communications networks might be vulnerable to eavesdropping.

Other parts that may need an explanation (minor issue): 
3.2.3 "OpenC2 endpoints supporting TLS 1.3 MUST NOT implement zero round trip time resumption (0-RTT)."  --- because it has been proved to be vulnerable to replay attacks.

"The TLS session MUST use non-NULL ciphersuites for authentication, integrity, and confidentiality. Sessions MAY be renegotiated within these constraints." --- NULL ciphersuites do not provide confidentiality.

**Comment by alevere** [comment]
I reviewed this wil Vasileios and agree that no-store is the correct solution here.
Created pull request #102 for this.

**Comment by dlemire60** [comment]
I agree with the change in PR #102 .

Part of @Vasileios-Mavroeidis issue also seemed to be that the lack of explanation was also problematic (e.g., the two other points at the bottom of his issue write-up). So do we also need to add some explanatory language for all three of these points?

**Comment by Vasileios-Mavroeidis** [comment]
@dlemire60 I think that it would be good to add some explanations. It's the justification of why we decided on the above. It aids understanding. I also need to give credits to John-Mark Gurney from New Context that also confirmed that no-store is the correct value.

**Comment by Vasileios-Mavroeidis** [comment]
Suggestions are:

-The TLS session MUST use non-NULL ciphersuites for authentication, integrity, and confidentiality (NULL ciphersuites do not provide confidentiality). Sessions MAY be renegotiated within these constraints.

-OpenC2 endpoints supporting TLS 1.3 MUST NOT implement zero round trip time resumption (0-RTT). Requests sent as part of 0-RTT resumption are vulnerable to what’s called a replay attack.

-All HTTP request and response messages containing OpenC2 payloads SHOULD include the "Cache-control:" header with a value of "no-store".  The "no-store" request directive indicates that a cache MUST NOT store any part of either this request or any response to it.

If you approve @dlemire60 @alevere  i can create a new pull request only for the explanations.

**Comment by dlemire60** [comment]
I approve.  Suggestions:

1. Add to the cache-control entry something like "OpenC2 command and response messages are intended to be exchange in cyber relevant time and not reused, therefore caching is inappropriate".  Feel free to tune up those words. What you have explains the option, but not the rationale for why we're choosing it.
2. Regarding 0-RTT, simply say "... vulnerable to a replay attack".

**Comment by jmbrule** [comment]
@dlemire60 , can I change the tag to this threat to 'resolved'?

**Comment by dlemire60** [comment]
I'll do that when I apply PR #102 .

**Comment by dlemire60** [comment]
Closing this issue now that PR #102 has been applied.
